name: streamlit_template
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PORT}
    container_name: streamlit_template
    hostname: streamlit_template
    command: ["streamlit", "run", "main.py", "--server.port=${PORT}", "--server.address=0.0.0.0"]
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./app:/var/www/app
